name: flutter_application_saveload_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  ini: ^2.1.0
  intl: ^0.20.2
  path: ^1.9.1
  top_snackbar_flutter: ^3.3.0
  http: ^1.4.0
  archive: ^4.0.7
  file_selector: ^1.0.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
